# Generated by Django 5.0.13 on 2025-06-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfiguration',
            name='database_server',
            field=models.CharField(choices=[('SQLITE', 'Sqlite3'), ('POSTGRES', 'Postgres')], default='SQLITE', help_text='Defines which backend database to be use.', max_length=16),
        ),
    ]
